services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: iowa-liquor-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrongPassword123"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "SQLCMD=/opt/mssql-tools18/bin/sqlcmd; [ -x $$SQLCMD ] || SQLCMD=/opt/mssql-tools/bin/sqlcmd; if [ -x $$SQLCMD ]; then $$SQLCMD -S localhost -U sa -P \"$$MSSQL_SA_PASSWORD\" -C -Q \"SELECT 1\"; else timeout 1 bash -c '</dev/tcp/localhost/1433'; fi",
        ]
      interval: 10s
      timeout: 5s
      retries: 20

  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: iowa-liquor-airflow
    working_dir: /opt/airflow/project
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/project/dags
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
      PYTHONPATH: /opt/airflow/project
      PROJECT_ROOT: /opt/airflow/project
      IOWA_START_DATE: "2023-01-01"
      IOWA_END_DATE: "2023-12-31"
      SOCRATA_LIMIT: "50000"
      SQLSERVER_HOST: sqlserver
      SQLSERVER_PORT: "1433"
      SQLSERVER_DATABASE: IowaLiquorDW
      SQLSERVER_USER: admin
      SQLSERVER_PASSWORD: admin
      SQLSERVER_BOOTSTRAP_USER: sa
      SQLSERVER_BOOTSTRAP_PASSWORD: YourStrongPassword123
      SQLSERVER_DRIVER: ODBC Driver 18 for SQL Server
      SQLSERVER_TRUST_CERTIFICATE: "yes"
    ports:
      - "8080:8080"
    volumes:
      - .:/opt/airflow/project
    command:
      - bash
      - -lc
      - |
        airflow db migrate
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || airflow users reset-password --username admin --password admin
        exec airflow standalone

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: iowa-liquor-streamlit
    working_dir: /opt/airflow/project
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      PYTHONPATH: /opt/airflow/project
      PROJECT_ROOT: /opt/airflow/project
      SQLSERVER_HOST: sqlserver
      SQLSERVER_PORT: "1433"
      SQLSERVER_DATABASE: IowaLiquorDW
      SQLSERVER_USER: admin
      SQLSERVER_PASSWORD: admin
      SQLSERVER_BOOTSTRAP_USER: sa
      SQLSERVER_BOOTSTRAP_PASSWORD: YourStrongPassword123
      SQLSERVER_DRIVER: ODBC Driver 18 for SQL Server
      SQLSERVER_TRUST_CERTIFICATE: "yes"
    ports:
      - "8501:8501"
    volumes:
      - .:/opt/airflow/project
    entrypoint: []
    command:
      - streamlit
      - run
      - /opt/airflow/project/app/streamlit_app.py
      - --server.address=0.0.0.0
      - --server.port=8501

volumes:
  sqlserver_data:
